# Based on default application configuration that all configurations inherit from.
# Defautl version:          https://raw.githubusercontent.com/causes/scss-lint/master/config/default.yml
# See config documentation: https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
# Inspired by:              http://davidtheclark.com/scss-lint-styleguide/

exclude: 'source/styles/print.scss'

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true

  ColorKeyword:
    enabled: false

  Comment:
    enabled: false #should be turned on later

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 5

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: true
    order: smacss # See for more info https://github.com/causes/scss-lint/blob/master/data/property-sort-orders/smacss.txt
    ignore_unspecified: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: tru
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  SelectorFormat:
    # Use custom regex to support Harry Robert BEM naming convention
    # http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/
    enabled: true
    convention: '^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)*(--[a-z0-9]([-]?[a-z0-9]+)*)?(_[a-z0-9]+){0,2}$' # or 'BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: false

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VendorPrefixes:
    enabled: false
    identifier_list: base
    include: []
    exclude: []

  ZeroUnit:
    enabled: false

  Compass::*:
    enabled: false
